In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
from IPython.core import prefilter
#From python list
arr = np.array([1,2,3,4,5])

#2D array(matrix)
arr_2d = np.array([[1,2,3],[4,5,6]])

#Using built in functions
zeros = np.zeros((3,4))
ones = np.ones((2,3))
range_arr = np.arange(0,10,2)
linspace = np.linspace(0,1,5)
identity = np.eye(3)
random_arr = np.random.rand(3,4)

print(zeros)
print("--------")
print(ones)
print("--------")
print(range_arr)
print("--------")
print(linspace)
print("--------")
print(identity)
print("-------")
print(random_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------
[[1. 1. 1.]
 [1. 1. 1.]]
--------
[0 2 4 6 8]
--------
[0.   0.25 0.5  0.75 1.  ]
--------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-------
[[0.97547369 0.54794377 0.59279389 0.29837576]
 [0.12392607 0.22204727 0.62949804 0.58573275]
 [0.61809129 0.13325862 0.63544338 0.98638264]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)


(2, 3)
int64
6
2


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
np.sum(a)

np.mean(a,axis=0)
np.mean(a,axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
np.max(a)
np.min(a)


np.int64(1)

In [ ]:
b = np.array([10,40,30,40,50])
np.argmax(b)

np.int64(4)

In [ ]:
import numpy as np

#crop yields for 4 farms over 5 seasons(in tons)
crop_yields = np.array([
    [12,13.2,14.1,13.8,15.2],
    [10,11.5,10.8,12.1,11.9],
    [15,14.8,16.2,15.5,16.8],
    [11,10.9,12.3,11.7,12.8]
])
print(' Crop yields array(tons): ')
print(crop_yields)
print(f'\nShape: {crop_yields.shape}')
print(f'Data type: {crop_yields.dtype}')
print(f'Total elements: {crop_yields.size}')
print(f'Number of dimensions: {crop_yields.ndim}')

 #Agricultural analysis operations
total_yield = np.sum(crop_yields)
avg_yield_per_farm = np.mean(crop_yields,axis=1)
avg_yield_per_season = np.mean(crop_yields,axis=0)
max_yield = np.max(crop_yields)
min_yield = np.min(crop_yields)

print(f'\nTotal production:{total_yield}tons')
print(f'Average yield per farm: {avg_yield_per_farm}tons')
print(f'Average yield per season: {avg_yield_per_season}tons')
print(f'Maximum yield: {max_yield}tons')
print(f'Minimum yield: {min_yield}tons')

 #Find best performing farm
best_farm = np.argmax(avg_yield_per_farm)

print(f'\nBest performing farm:Farm{best_farm + 1}')
print(f'Their average yield:{avg_yield_per_farm[best_farm]: 2f}tons')

 Crop yields array(tons): 
[[12.  13.2 14.1 13.8 15.2]
 [10.  11.5 10.8 12.1 11.9]
 [15.  14.8 16.2 15.5 16.8]
 [11.  10.9 12.3 11.7 12.8]]

Shape: (4, 5)
Data type: float64
Total elements: 20
Number of dimensions: 2

Total production:261.6tons
Average yield per farm: [13.66 11.26 15.66 11.74]tons
Average yield per season: [12.    12.6   13.35  13.275 14.175]tons
Maximum yield: 16.8tons
Minimum yield: 10.0tons

Best performing farm:Farm3
Their average yield: 15.660000tons


In [10]:
import numpy as np

#Marks of a students in 5 subjects

marks = np.array([
    [78,85,90,88,92],  #student1
    [65,70,72,68,75],   #student2
    [70,75,80,78,82],   #student3
    [88,92,95,90,94]   #student4
])
print("Students marks array: ")
print(marks)

print(f"\nShape: {marks.shape}")
print(f"Data type: {marks.dtype}")
print(f"Total elements: {marks.size}")
print(f"Number of dimensions: {marks.ndim}")

total_marks = np.sum(marks)
avg_marks_per_student = np.mean(marks,axis=1)
avg_marks_per_subject = np.mean(marks,axis=0)
max_marks = np.max(marks)
min_marks = np.min(marks)

print(f"\nTotal marks of all students: {total_marks}")
print(f"Average marks per student: {avg_marks_per_student}")
print(f"Average marks per subject: {avg_marks_per_subject}")
print(f"Maximum marks: {max_marks}")
print(f"Minimum marks: {min_marks}")

#find the best performing student
best_student = np.argmax(avg_marks_per_student)
print(f"\nBest Performing Student: Student{best_student + 1}")
print(f"Their average marks: {avg_marks_per_student[best_student]: .2f}")

Students marks array: 
[[78 85 90 88 92]
 [65 70 72 68 75]
 [70 75 80 78 82]
 [88 92 95 90 94]]

Shape: (4, 5)
Data type: int64
Total elements: 20
Number of dimensions: 2

Total marks of all students: 1627
Average marks per student: [86.6 70.  77.  91.8]
Average marks per subject: [75.25 80.5  84.25 81.   85.75]
Maximum marks: 95
Minimum marks: 65

Best Performing Student: Student4
Their average marks:  91.80
