In [ ]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A @ B

array([[19, 22],
       [43, 50]])

In [17]:
import numpy as np

B = np.array([[1,2],[3,4]])
A = np.array([[5,6],[7,8]])
C = np.array([[9,10],[11,12]])
D = A @ B
print(D)
E = np.dot(A,B)
print(E)

[[23 34]
 [31 46]]
[[23 34]
 [31 46]]


In [20]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A + B
print("Matrix addition: ")
print(C)

Matrix addition: 
[[ 6  8]
 [10 12]]


In [21]:
C = A*B
print("Matrix multiplication: ")
print(C)

Matrix multiplication: 
[[ 5 12]
 [21 32]]


In [23]:
#Transpose of a matrix
print("Transpose of a matrix: ")
print(A.T)
print(B.T)

Transpose of a matrix: 
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [25]:
#determinant of a matrix
det = np.linalg.det(A)
print(det)

-2.0000000000000004


In [26]:
#inverse of a matrix
A = np.array([[1,2],[3,4]])
inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [27]:
#rank of a matrix
rank = np.linalg.matrix_rank(A)
print(rank)

2


In [29]:
values,vectors = np.linalg.eig(A)
print(values)
print(vectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [31]:
#linear equations(Ax = b)
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

x = np.linalg.solve(A,B)
print(x)

[[-3. -4.]
 [ 4.  5.]]
