In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
for(int i=0;i<100;i++)
{
    sum+=array[i];
}

SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-579458894.py, line 1)

In [10]:
#1-Dimensional arrays
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [14]:
#2-Dimensional arrays
import numpy as np
arr = np.array([[2,4,6,8,0],[2,2,6,8,3]])
print(arr)

[[2 4 6 8 0]
 [2 2 6 8 3]]


In [19]:
#3-Dimensional arrays
import numpy as np
array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
import numpy as np

d=np.array([[[12],[24]],[[36],[48]]])
a=np.array(365)
c=np.array([[12,24,36],[48,60,72]])
b=np.array([12,24])

print(d.ndim)
print(a.ndim)
print(c.ndim)
print(b.ndim)

3
0
2
1


In [28]:
import numpy as np
array = np.array([22,24,26,28], ndmin=5)

print(array)
print('number of dimensions:', arr.ndim)

[[[[[22 24 26 28]]]]]
number of dimensions: 3
